# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b3fc7a0aaf0a4958d48298644780311958e23ad4d0dc8d3d8c66970d70f6c4dd3dc92cc93fe7dd000bb64578f2940eef64a803dd373dc5397780a929f968a64

test:
  secret_key_base: 61a17c877a0c22a7de14a01b3a81c41831e13cd326648a94350430880e33832cafed0c794bec158c9c40e4157a23a6e6bca98f0a101c74179d28c91b2f585834

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
